name: kaggle-titanic
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - keras
  - xgboost
  - jupyterlab
  - ipykernel
  - pip:
      - tensorflow
